In [2]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


import seaborn as sns
sns.set()  #  Will import Seaborn functionalities
# we don't like warnings
# you can comment the following 2 lines if you'd like to
import warnings
warnings.filterwarnings('ignore')

In [3]:
# Disply all Columns
pd.options.display.max_columns=10

In [4]:
bank_data = pd.read_csv('bank_data.csv')

In [5]:
bank_data.head()

,user_id,zipcode,state,cc_number,cc_limit,date,transaction,long,lat
0,29421272,3280,NH,4.983680e+15,10000,8/11/2016 19:14,44.65,-72.174098,43.156873
1,29421272,3280,NH,4.983680e+15,10000,6/10/2016 22:09,5.68,-72.131747,43.213248
2,29421272,3280,NH,4.983680e+15,10000,7/27/2016 4:18,63.19,-72.022366,43.161782
3,29421272,3280,NH,4.983680e+15,10000,5/27/2016 0:39,122.04,-72.159013,43.235530
4,29421272,3280,NH,4.983680e+15,10000,8/15/2016 22:14,53.66,-72.169355,43.170859

In [7]:
bank_data.columns

Index(['user_id', 'zipcode', 'state', 'cc_number', 'cc_limit', 'date',
       'transaction', 'long', 'lat'],
      dtype='object')

In [8]:
bank_data.shape

(233043, 9)

In [10]:
bank_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233043 entries, 0 to 233042
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   user_id      233043 non-null  int64
 1   zipcode      233043 non-null  int64
 2   state        233043 non-null  object
 3   cc_number    233043 non-null  float64
 4   cc_limit     233043 non-null  int64
 5   date         233043 non-null  object
 6   transaction  233043 non-null  float64
 7   long         233043 non-null  float64
 8   lat          233043 non-null  float64
dtypes: float64(4), int64(3), object(2)
memory usage: 16.0+ MB

In [11]:
# Number of rows
len(bank_data)  # for traceability 576 rows imported

233043

In [12]:
bank_data.describe()

,user_id,zipcode,cc_number,cc_limit,transaction,long,lat
count,2.330430e+05,233043.000000,2.330430e+05,233043.000000,233043.000000,233043.000000,233043.000000
mean,5.065137e+07,18411.574851,5.402803e+15,12801.478697,77.515636,-76.486116,40.914953
std,2.930390e+07,24531.477690,2.527963e+15,5015.120164,122.244587,20.361250,5.396546
min,1.541420e+05,690.000000,1.048240e+15,2000.000000,0.010000,-179.392887,-66.735588
25%,2.426510e+07,3280.000000,3.204630e+15,9000.000000,27.160000,-80.220837,40.421894
50%,5.150837e+07,5343.000000,5.281010e+15,12000.000000,52.240000,-72.807566,42.490085
75%,7.581502e+07,18612.000000,7.474740e+15,18000.000000,88.020000,-72.091062,43.180160
max,9.974543e+07,98401.000000,9.984440e+15,20000.000000,999.970000,179.917514,78.914330

In [13]:
bank_data.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
user_id,233043.0,5.065137e+07,2.930390e+07,1.541420e+05,2.426510e+07,5.150837e+07,7.581502e+07,9.974543e+07
zipcode,233043.0,1.841157e+04,2.453148e+04,6.900000e+02,3.280000e+03,5.343000e+03,1.861200e+04,9.840100e+04
cc_number,233043.0,5.402803e+15,2.527963e+15,1.048240e+15,3.204630e+15,5.281010e+15,7.474740e+15,9.984440e+15
cc_limit,233043.0,1.280148e+04,5.015120e+03,2.000000e+03,9.000000e+03,1.200000e+04,1.800000e+04,2.000000e+04
transaction,233043.0,7.751564e+01,1.222446e+02,1.000000e-02,2.716000e+01,5.224000e+01,8.802000e+01,9.999700e+02
long,233043.0,-7.648612e+01,2.036125e+01,-1.793929e+02,-8.022084e+01,-7.280757e+01,-7.209106e+01,1.799175e+02
lat,233043.0,4.091495e+01,5.396546e+00,-6.673559e+01,4.042189e+01,4.249008e+01,4.318016e+01,7.891433e+01

In [16]:
from skimpy import skim

In [18]:
skim(bank_data)

╭──────────────────────────────────────────────── skimpy summary ─────────────────────────────────────────────────╮
│          Data Summary                Data Types                                                                 │
│ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓ ┏━━━━━━━━━━━━━┳━━━━━━━┓                                                          │
│ ┃ dataframe         ┃ Values ┃ ┃ Column Type ┃ Count ┃                                                          │
│ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩ ┡━━━━━━━━━━━━━╇━━━━━━━┩                                                          │
│ │ Number of rows    │ 233043 │ │ float64     │ 4     │                                                          │
│ │ Number of columns │ 9      │ │ int32       │ 3     │                                                          │
│ └───────────────────┴────────┘ │ string      │ 2     │                                                          │
│                                └─────────────┴───────┘                                                          │
│                                                     number                                                      │
│ ┏━━━━━━━━━━━━┳━━━━┳━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓  │
│ ┃ column_nam ┃    ┃      ┃            ┃           ┃            ┃           ┃            ┃           ┃        ┃  │
│ ┃ e          ┃ NA ┃ NA % ┃ mean       ┃ sd        ┃ p0         ┃ p25       ┃ p75        ┃ p100      ┃ hist   ┃  │
│ ┡━━━━━━━━━━━━╇━━━━╇━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩  │
│ │ user_id    │  0 │    0 │   51000000 │  29000000 │     150000 │  24000000 │   76000000 │ 100000000 │ ▇▇▆▇▇█ │  │
│ │ zipcode    │  0 │    0 │      18000 │     25000 │        690 │      3300 │      19000 │     98000 │  █▁ ▁  │  │
│ │ cc_number  │  0 │    0 │ 5400000000 │ 250000000 │ 1000000000 │ 320000000 │ 7500000000 │     1e+16 │ ▇▇█▇▇▆ │  │
│ │            │    │      │     000000 │   0000000 │     000000 │   0000000 │     000000 │           │        │  │
│ │ cc_limit   │  0 │    0 │      13000 │      5000 │       2000 │      9000 │      18000 │     20000 │ ▁▃█▃▆▇ │  │
│ │ transactio │  0 │    0 │         78 │       120 │       0.01 │        27 │         88 │      1000 │   █    │  │
│ │ n          │    │      │            │           │            │           │            │           │        │  │
│ │ long       │  0 │    0 │        -76 │        20 │       -180 │       -80 │        -72 │       180 │    █   │  │
│ │ lat        │  0 │    0 │         41 │       5.4 │        -67 │        40 │         43 │        79 │     █  │  │
│ └────────────┴────┴──────┴────────────┴───────────┴────────────┴───────────┴────────────┴───────────┴────────┘  │
│                                                     string                                                      │
│ ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┓  │
│ ┃ column_name               ┃ NA      ┃ NA %       ┃ words per row                ┃ total words              ┃  │
│ ┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━┩  │
│ │ state                     │       0 │          0 │                            1 │                   230000 │  │
│ │ date                      │       0 │          0 │                            1 │                   230000 │  │
│ └───────────────────────────┴─────────┴────────────┴──────────────────────────────┴──────────────────────────┘  │
╰────────────────────────────────────────────────────── End ──────────────────────────────────────────────────────╯